export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_WITHOUT_REDIRECT = 'AUTH_LOGOUT_WITHOUT_REDIRECT';
export const AUTH_FETCH_CURRENT_USER = 'AUTH_FETCH_CURRENT_USER';
export const AUTH_REFRESH = 'AUTH_REFRESH';
export const AUTH_FETCH_USER_LEVEL_DATA = 'AUTH_FETCH_USER_LEVEL_DATA';

export const PAGES_FETCH_MENUS = 'PAGES_FETCH_MENUS';
export const PAGES_ADD_PAGE = 'PAGES_ADD_PAGE';
export const PAGES_SET_CURRENT_PAGE = 'PAGES_SET_CURRENT_PAGE';
export const PAGES_FETCH_PAGE_PERMISSIONS = 'PAGES_FETCH_PAGE_PERMISSIONS';

export const PHARMACIES_FETCH_PHARMACIES = 'PHARMACIES_FETCH_PHARMACIES';

export const SETTINGS_FETCH_SETTINGS = 'SETTINGS_FETCH_SETTINGS';
export const SETTINGS_CREATE_INVITATIONS = 'SETTINGS_CREATE_INVITATIONS';
export const SETTINGS_SET_THEME = 'SETTINGS_SET_THEME';
export const SETTINGS_SET_LANGUAGE = 'SETTINGS_SET_LANGUAGE';
export const SETTINGS_SET_CURRENT_VIEWPORT = 'SETTINGS_SET_CURRENT_VIEWPORT';

export const TRAININGS_FETCH_ALL_SERIES = 'TRAININGS_FETCH_ALL_SERIES';
export const TRAININGS_FETCH_ONE_SERIES = 'TRAININGS_FETCH_ONE_SERIES';
export const TRAININGS_UPDATE_CURRENT_TRAINING_SERIES = 'TRAININGS_UPDATE_CURRENT_TRAINING_SERIES';
export const TRAININGS_UPDATE_CURRENT_TRAINING = 'TRAININGS_UPDATE_CURRENT_TRAINING';

export const TAXONOMIES_FETCH_ALL = 'TAXONOMIES_FETCH_ALL';
export const TAXONOMIES_FETCH_TRAINING_CATEGORIES = 'TAXONOMIES_FETCH_TRAINING_CATEGORIES';
export const TAXONOMIES_FETCH_DOWNLOAD_CATEGORIES = 'TAXONOMIES_FETCH_DOWNLOAD_CATEGORIES';
export const TAXONOMIES_FETCH_DOWNLOAD_PRODUCTS = 'TAXONOMIES_FETCH_DOWNLOAD_PRODUCTS';
export const TAXONOMIES_FETCH_DOWNLOAD_MEDIATYPES = 'TAXONOMIES_FETCH_DOWNLOAD_MEDIATYPES';

export const SURVEYS_FETCH_ALL = 'SURVEY_FETCH_ALL';
export const SURVEYS_FETCH_ONE = 'SURVEY_FETCH_ONE';
export const SURVEYS_STORE_RESULT = 'SURVEY_STORE_RESULT';
export const LATESTS_SURVEYS = 'LATEST_SURVEYS';

export const DETAILERS_JOB_FETCH_INFORMATIONAL_TRAININGS = 'DETAILERS_JOB_FETCH_INFORMATIONAL_TRAININGS';
export const DETAILERS_JOB_FETCH_SAVED_STATES = 'DETAILERS_JOB_FETCH_SAVED_STATES';

export const DOWNLOADS_FETCH_ALL = 'DOWNLOADS_FETCH_ALL';
export const DOWNLOADS_FETCH_ONE = 'DOWNLOADS_FETCH_ONE';

export const KNOWLEDGE_BASE_FETCH_ALL = 'KNOWLEDGE_BASE_FETCH_ALL';
export const KNOWLEDGE_BASE_FETCH_ONE = 'KNOWLEDGE_BASE_FETCH_ONE';

export const RAFFLE_FETCH_ALL = 'RAFFLE_FETCH_ALL';
export const RAFFLE_FETCH_ONE = 'RAFFLE_FETCH_ONE';

export const FORMS_FETCH_FORM = 'FORMS_FETCH_FORM';
export const VOUCHERS_FETCH_ALL = 'VOUCHERS_FETCH_ALL';
export const VOUCHERS_REDEEM_VOUCHER = 'VOUCHERS_REDEEM_VOUCHER';
export const VOUCHERS_EXCHANGE_POINTS = 'VOUCHERS_EXCHANGE_POINTS';
export const FILTER_TRAININGS = 'FILTER_TRAININGS';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const CLEAR_TRAININGS = 'CLEAR_TRAININGS';
export const SHOW_TAB = 'SHOW_TAB';
export const SHOW_TAB_CATEGORY = 'SHOW_TAB_CATEGORY';
export const CLICK = 'CLICK';
export const CLICK_CATEGORY = 'CLICK_CATEGORY';
export const SCROLL = 'SCROLL';
export const SETCATEGORY = 'SETCATEGORY';

export const SALES_REP_FETCH_BY_EXPERT_CODE = 'SALES_REP_FETCH_BY_EXPERT_CODE';

export const PHARMACIES_FETCH_PUN = 'PHARMACIES_FETCH_PUN';
export const PHARMACIES_UPDATE_PUN_ACTION = 'PHARMACIES_UPDATE_PUN_ACTION';
