export const AUTH_UPDATE_TOKEN = 'AUTH_UPDATE_TOKEN';
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER';
export const AUTH_UPDATE_SHOW_UPDATE_PHARMACY_MODAL = 'AUTH_UPDATE_SHOW_UPDATE_PHARMACY_MODAL';
export const AUTH_UPDATE_USER_LEVEL_DATA = 'AUTH_UPDATE_USER_LEVEL_DATA';

export const PAGES_UPDATE = 'PAGES_UPDATE';

export const PAGES_UPDATE_CURRENT = 'PAGES_UPDATE_CURRENT';
export const PAGES_UPDATE_MENUS = 'PAGES_UPDATE_MENUS';
export const PAGES_UPDATE_PAGE_PERMISSIONS = 'PAGES_UPDATE_PAGE_PERMISSIONS';

export const PHARMACIES_UPDATE_PHARMACIES = 'PHARMACIES_UPDATE_PHARMACIES';

export const SETTINGS_UPDATE_SETTINGS = 'SETTINGS_UPDATE_SETTINGS';
export const SETTINGS_UPDATE_THEME = 'SETTINGS_UPDATE_THEME';
export const SETTINGS_UPDATE_LANGUAGE = 'SETTINGS_UPDATE_LANGUAGE';
export const SETTINGS_UPDATE_CURRENT_VIEWPORT = 'SETTINGS_UPDATE_CURRENT_VIEWPORT';
export const SETTINGS_UPDATE_NOTIFICATION = 'SETTINGS_UPDATE_NOTIFICATION';
export const SETTINGS_CLEAR_NOTIFICATION = 'SETTINGS_CLEAR_NOTIFICATION';
export const SETTINGS_LOADED = 'SETTINGS_LOADED';

export const TRAININGS_UPDATE_TRAINING_SERIES = 'TRAININGS_UPDATE_TRAINING_SERIES';
export const TRAININGS_UPDATE_PREMIUM_TRAINING_SERIES = 'TRAININGS_UPDATE_PREMIUM_TRAINING_SERIES';
export const TRAININGS_UPDATE_PRODUCT_TRAINING_SERIES = 'TRAININGS_UPDATE_PRODUCT_TRAINING_SERIES';
export const TRAININGS_UPDATE_CATEGORY_TRAINING_SERIES = 'TRAININGS_UPDATE_CATEGORY_TRAINING_SERIES';
export const TRAININGS_UPDATE_LATEST_PREMIUM_TRAINING_SERIES = 'TRAININGS_UPDATE_LATEST_PREMIUM_TRAINING_SERIES';
export const TRAININGS_UPDATE_SURVEYS_TRAINING_SERIES = 'TRAININGS_UPDATE_SURVEYS_TRAINING_SERIES';
export const TRAININGS_UPDATE_AVAILABLE_TRAINING_SERIES = 'TRAININGS_UPDATE_AVAILABLE_TRAINING_SERIES';
export const TRAININGS_UPDATE_ONE_TRAINING_SERIES = 'TRAININGS_UPDATE_ONE_TRAINING_SERIES';
export const TRAININGS_SET_CURRENT_TRAINING_SERIES = 'TRAININGS_SET_CURRENT_TRAINING_SERIES';
export const TRAININGS_SET_CURRENT_TRAINING = 'TRAININGS_SET_CURRENT_TRAINING';
export const TRAININGS_SET_CURRENT_LESSON_ID = 'TRAININGS_SET_CURRENT_LESSON_ID';
export const TRAININGS_SET_CURRENT_TRAINING_ID = 'TRAININGS_SET_CURRENT_TRAINING_ID';

export const TAXONOMIES_UPDATE_ALL_TAXONOMIES = 'TAXONOMIES_UPDATE_ALL_TAXONOMIES';
export const TAXONOMIES_UPDATE_TRAINING_CATEGORIES = 'TAXONOMIES_UPDATE_TRAINING_CATEGORIES';
export const TAXONOMIES_UPDATE_DOWNLOAD_CATEGORIES = 'TAXONOMIES_UPDATE_DOWNLOAD_CATEGORIES';
export const TAXONOMIES_UPDATE_DOWNLOAD_PRODUCTS = 'TAXONOMIES_UPDATE_DOWNLOAD_PRODUCTS';
export const TAXONOMIES_UPDATE_DOWNLOAD_MEDIATYPES = 'TAXONOMIES_UPDATE_DOWNLOAD_MEDIATYPES';

export const SURVEYS_UPDATE_SURVEYS = 'SURVEYS_UPDATE_SURVEYS';
export const SURVEYS_UPDATE_CURRENT_SURVEY = 'SURVEYS_UPDATE_CURRENT_SURVEY';
export const UPDATE_LATEST_SURVEYS = 'UPDATE_LATEST_SURVEYS';
export const UPDATE_SURVEY_ANSWERS = 'UPDATE_SURVEY_ANSWERS';

export const DETAILERS_JOB_UPDATE_INFORMATIONAL_TRAININGS = 'DETAILERS_JOB_UPDATE_INFORMATIONAL_TRAININGS';
export const DETAILERS_JOB_UPDATE_SAVED_STATES = 'DETAILERS_JOB_UPDATE_SAVED_STATES';
export const DETAILERS_JOB_UPDATE_SAVED_STATE = 'DETAILERS_JOB_UPDATE_SAVED_STATE';
export const DETAILERS_JOB_REMOVE_SAVED_STATE = 'DETAILERS_JOB_REMOVE_SAVED_STATE';

export const DOWNLOADS_UPDATE_DOWNLOADS = 'DOWNLOADS_UPDATE_DOWNLOADS';
export const DOWNLOADS_UPDATE_CURRENT_DOWNLOAD = 'DOWNLOADS_UPDATE_CURRENT_DOWNLOAD';

export const KNOWLEDGE_BASE_UPDATE_KNOWLEDGE_BASE = 'KNOWLEDGE_BASE_UPDATE_KNOWLEDGE_BASE';
export const KNOWLEDGE_BASE_UPDATE_CURRENT_KNOWLEDGE_BASE = 'KNOWLEDGE_BASE_UPDATE_CURRENT_KNOWLEDGE_BASE';

export const RAFFLE_UPDATE_RAFFLE = 'RAFFLE_UPDATE_RAFFLE';
export const RAFFLE_UPDATE_CURRENT_RAFFLE = 'RAFFLE_UPDATE_CURRENT_RAFFLE';

export const FORMS_UPDATE_FORM = 'FORMS_UPDATE_FORM';
export const VOUCHERS_UPDATE_ALL = 'VOUCHERS_UPDATE_ALL';
export const VOUCHERS_UPDATE_NOTIFICATION = 'VOUCHERS_UPDATE_NOTIFICATION';
export const VOUCHERS_CLEAR_NOTIFICATION = 'VOUCHERS_CLEAR_NOTIFICATION';
export const FILTER_TRAININGSM = 'FILTER_TRAININGSM';
export const CLEAR_TRAININGSM = 'CLEAR_TRAININGSM';
export const SHOW_TABM = 'SHOW_TABM';
export const SHOW_TAB_CATEGORYM = 'SHOW_TAB_CATEGORYM';
export const CLICKM = 'CLICKM';
export const CLICK_CATEGORYM = 'CLICK_CATEGORYM';
export const SETCATEGORYM = 'SETCATEGORYM';
export const PHARMACIES_UPDATE_PUN = 'PHARMACIES_UPDATE_PUN';

export const SALES_REP_UPDATE_SALES_REP_NAME = 'SALES_REP_UPDATE_SALES_REP_NAME';
export const SALES_REP_RESET_SALES_REP_NAME = 'SALES_REP_RESET_SALES_REP_NAME';
